NCAR-version: v1.0
environmental_conditions:
  pressure:
    evolving: false
    initial_value: [101253.3]
    units: Pa
  temperature:
    evolving: false
    initial_value: [272.5]
    units: K
  air_concetration:
    initial_value: 1.0
initial_state:
  A: 
   initial_value: [1.0]
   units: mol m-3
model_info:
  chemistry_time_step:
    units: sec
    value: 1.0
  evolving_conditions:
    exist: false
  output_time_step:
    units: sec
    value: 1.0
  simulation_length:
    units: sec
    value: 100.0
  cells: 1
reactions:
- coefficients:
    k0_A: 4.0e-18 
  products:
    B: 1.0
  reactants:
    A: 1.0
  type: TROE
- coefficients:
    k0_A: 1.2e-12
    k0_B: 167.0
    k0_C: 3.0
    kinf_A: 136.0
    kinf_B: 5.0
    kinf_C: 24.0
    Fc: 0.9
    N: 0.8
  products:
    C: 1.0
  reactants:
    B: 1.0
  type: TROE
  time_unit: min
species:
- description: A 
  name: A
- description: B 
  name: B
- description: C 
  name: C
