site_name: "TChem-atm: a kinetic solver for atmospheric chemistry"

theme:
  name: material
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: cyan
    toggle:
      icon: material/weather-night
      name: Switch to light mode
  features:
    - navigation.indices
    - navigation.instant
    - navigation.sections
    - navigation.top

  markdown_extensions:
    - admonition
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.tabbed:
      alternate_style: true
    - pymdownx.arithmatex:
      generic: true
    - tables

  extra_javascript:
    - javascript/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

  repo_url: https://github.com/PCLAeroParams/TChem-atm
