#ifndef __TCHEM_IMPL_MOSAIC_MTEM_HPP__
#define __TCHEM_IMPL_MOSAIC_MTEM_HPP__

  KOKKOS_INLINE_FUNCTION static
  void MTEM_compute_log_gamZ(const MosaicModelData<DeviceType>& mosaic,
                             const real_type& aH2O,
                             real_type_2d_view_type log_gamZ) {

    real_type log_gamZ_ = 0.0;

    // sulfate-poor species
    ordinal_type jA = mosaic.jhno3;
    fnlog_gamZ(mosaic, jA, mosaic.jnh4so4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnh4so4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnh4no3, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnh4no3) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnh4cl, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnh4cl) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jna2so4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jna2so4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnano3, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnano3) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnacl, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnacl) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jcano3, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jcano3) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jcacl2, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jcacl2) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jhno3, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jhno3) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jhcl, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jhcl) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jh2so4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jh2so4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnh4hso4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnh4hso4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jlvcite, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jlvcite) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnahso4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnahso4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jna3hso4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jna3hso4) = log_gamZ_;

    jA = mosaic.jhcl;
    fnlog_gamZ(mosaic, jA, mosaic.jnh4so4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnh4so4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnh4no3, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnh4no3) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnh4cl, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnh4cl) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jna2so4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jna2so4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnano3, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnano3) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnacl, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnacl) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jcano3, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jcano3) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jcacl2, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jcacl2) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jhno3, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jhno3) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jhcl, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jhcl) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jh2so4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jh2so4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnh4hso4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnh4hso4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jlvcite, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jlvcite) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnahso4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnahso4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jna3hso4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jna3hso4) = log_gamZ_;

    jA = mosaic.jnh4so4;
    fnlog_gamZ(mosaic, jA, mosaic.jnh4so4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnh4so4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnh4no3, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnh4no3) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnh4cl, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnh4cl) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jna2so4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jna2so4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnano3, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnano3) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnacl, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnacl) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jcano3, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jcano3) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jcacl2, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jcacl2) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jhno3, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jhno3) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jhcl, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jhcl) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jh2so4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jh2so4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnh4hso4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnh4hso4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jlvcite, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jlvcite) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnahso4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnahso4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jna3hso4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jna3hso4) = log_gamZ_;

    jA = mosaic.jnh4no3;
    fnlog_gamZ(mosaic, jA, mosaic.jnh4so4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnh4so4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnh4no3, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnh4no3) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnh4cl, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnh4cl) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jna2so4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jna2so4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnano3, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnano3) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnacl, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnacl) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jcano3, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jcano3) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jcacl2, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jcacl2) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jhno3, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jhno3) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jhcl, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jhcl) = log_gamZ_;

    jA = mosaic.jnh4cl;
    fnlog_gamZ(mosaic, jA, mosaic.jnh4so4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnh4so4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnh4no3, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnh4no3) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnh4cl, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnh4cl) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jna2so4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jna2so4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnano3, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnano3) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnacl, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnacl) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jcano3, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jcano3) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jcacl2, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jcacl2) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jhno3, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jhno3) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jhcl, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jhcl) = log_gamZ_;

    jA = mosaic.jna2so4;
    fnlog_gamZ(mosaic, jA, mosaic.jnh4so4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnh4so4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnh4no3, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnh4no3) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnh4cl, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnh4cl) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jna2so4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jna2so4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnano3, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnano3) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnacl, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnacl) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jcano3, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jcano3) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jcacl2, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jcacl2) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jhno3, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jhno3) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jhcl, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jhcl) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jh2so4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jh2so4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnh4hso4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnh4hso4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jlvcite, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jlvcite) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnahso4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnahso4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jna3hso4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jna3hso4) = log_gamZ_;

    jA = mosaic.jnano3;
    fnlog_gamZ(mosaic, jA, mosaic.jnh4so4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnh4so4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnh4no3, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnh4no3) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnh4cl, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnh4cl) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jna2so4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jna2so4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnano3, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnano3) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnacl, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnacl) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jcano3, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jcano3) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jcacl2, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jcacl2) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jhno3, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jhno3) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jhcl, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jhcl) = log_gamZ_;

    jA = mosaic.jnacl;
    fnlog_gamZ(mosaic, jA, mosaic.jnh4so4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnh4so4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnh4no3, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnh4no3) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnh4cl, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnh4cl) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jna2so4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jna2so4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnano3, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnano3) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnacl, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnacl) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jcano3, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jcano3) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jcacl2, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jcacl2) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jhno3, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jhno3) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jhcl, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jhcl) = log_gamZ_;

    jA = mosaic.jcano3;
    fnlog_gamZ(mosaic, jA, mosaic.jnh4so4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnh4so4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnh4no3, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnh4no3) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnh4cl, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnh4cl) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jna2so4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jna2so4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnano3, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnano3) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnacl, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnacl) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jcano3, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jcano3) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jcacl2, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jcacl2) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jhno3, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jhno3) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jhcl, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jhcl) = log_gamZ_;

    jA = mosaic.jcacl2;
    fnlog_gamZ(mosaic, jA, mosaic.jnh4so4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnh4so4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnh4no3, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnh4no3) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnh4cl, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnh4cl) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jna2so4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jna2so4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnano3, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnano3) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnacl, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnacl) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jcano3, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jcano3) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jcacl2, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jcacl2) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jhno3, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jhno3) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jhcl, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jhcl) = log_gamZ_;

    // sulfate-rich species
    jA = mosaic.jh2so4;
    fnlog_gamZ(mosaic, jA, mosaic.jh2so4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jh2so4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnh4hso4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnh4hso4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jlvcite, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jlvcite) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnh4so4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnh4so4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnahso4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnahso4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jna3hso4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jna3hso4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jna2so4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jna2so4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jhno3, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jhno3) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jhcl, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jhcl) = log_gamZ_;

    jA = mosaic.jhhso4;
    fnlog_gamZ(mosaic, jA, mosaic.jh2so4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jh2so4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnh4hso4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnh4hso4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jlvcite, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jlvcite) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnh4so4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnh4so4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnahso4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnahso4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jna3hso4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jna3hso4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jna2so4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jna2so4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jhno3, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jhno3) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jhcl, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jhcl) = log_gamZ_;

    jA = mosaic.jnh4hso4;
    fnlog_gamZ(mosaic, jA, mosaic.jh2so4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jh2so4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnh4hso4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnh4hso4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jlvcite, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jlvcite) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnh4so4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnh4so4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnahso4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnahso4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jna3hso4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jna3hso4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jna2so4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jna2so4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jhno3, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jhno3) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jhcl, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jhcl) = log_gamZ_;

    jA = mosaic.jlvcite;
    fnlog_gamZ(mosaic, jA, mosaic.jh2so4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jh2so4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnh4hso4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnh4hso4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jlvcite, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jlvcite) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnh4so4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnh4so4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnahso4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnahso4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jna3hso4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jna3hso4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jna2so4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jna2so4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jhno3, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jhno3) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jhcl, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jhcl) = log_gamZ_;

    jA = mosaic.jnahso4;
    fnlog_gamZ(mosaic, jA, mosaic.jh2so4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jh2so4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnh4hso4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnh4hso4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jlvcite, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jlvcite) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnh4so4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnh4so4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnahso4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnahso4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jna3hso4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jna3hso4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jna2so4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jna2so4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jhno3, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jhno3) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jhcl, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jhcl) = log_gamZ_;

    jA = mosaic.jna3hso4;
    fnlog_gamZ(mosaic, jA, mosaic.jh2so4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jh2so4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnh4hso4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnh4hso4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jlvcite, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jlvcite) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnh4so4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnh4so4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jnahso4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jnahso4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jna3hso4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jna3hso4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jna2so4, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jna2so4) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jhno3, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jhno3) = log_gamZ_;
    fnlog_gamZ(mosaic, jA, mosaic.jhcl, aH2O, log_gamZ_);
    log_gamZ(jA,mosaic.jhcl) = log_gamZ_;
  } // MTEM_compute_log_gamZ

#endif