
# This file was generated by PartMC-mosaic.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.je=[[         1],]
input.aH2O_a=[[  0.86918676121422112E+000],]
input.molality=[[  0.25344302823602594E-316],]
# Output data is stored here.
output = Object()
output.molality=[[  0.39937951815127040E+001],]
