
# This file was generated by PartMC-mosaic.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.vol_wet_a=[[  0.11988115123653083E-014],]
input.num_a=[[  0.11776320829312793E+002],]
input.aH2O_a=[[  0.94750573512584713E+000],]
input.sigma_water=[[  0.73205135929453977E-001],]
input.T_K=[[  0.29005740000000003E+003],]
# Output data is stored here.
output = Object()
output.vol_wet_a=[[  0.11988115123653083E-014],]
output.num_a=[[  0.11776320829312793E+002],]
output.aH2O_a=[[  0.94750573512584713E+000],]
output.sigma_water=[[  0.73205135929453977E-001],]
output.T_K=[[  0.29005740000000003E+003],]
output.volume_a=[[  0.11988115123653083E-014],]
output.DpmV=[[  0.57931426191945094E-005],]
output.sigma_soln=[[  0.26454241147629451E+001],]
output.kelvin=[[  0.10013642526169526E+001],]
