
# This file was generated by PartMC-mosaic.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.j_index=[[         1],]
input.T_K=[[  0.29142360000000002E+003],]
# Output data is stored here.
output = Object()
output.drh_mutual=[[  0.80202077162854152E+002],]
