
# This file was generated by PartMC-mosaic.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.Keq_298=[[  0.57640000000000001E+002],]
input.a=[[  0.13789999999999999E+002],]
input.b=[[ -0.53899999999999997E+001],]
input.T=[[  0.29142360000000002E+003],]
input.Keq=[[  0.10000000000000000E+002],]
# Output data is stored here.
output = Object()
output.Keq=[[  0.79354086448815266E+002],]
