
# This file was generated by PartMC-mosaic.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.Po_298=[[  0.57000000000000003E-004],]
input.DH=[[  0.15600000000000000E+003],]
input.T_K=[[  0.29142360000000002E+003],]
input.Po=[[  0.29005922138061241E-316],]
# Output data is stored here.
output = Object()
output.Po=[[  0.13336165682111354E-004],]
