
# This file was generated by PartMC-mosaic.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.jA=[[        18],]
input.jE=[[         1],]
input.aH2O=[[  0.86918676121422112E+000],]
input.log_gamZ=[[  0.16970466628670999E+000],]
# Output data is stored here.
output = Object()
output.log_gamZ=[[ -0.72387466129594991E+000],]
