
# This file was generated by PartMC-mosaic.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.rkn=[[  0.11485877229304073E+002],]
input.a=[[  0.10000000149011612E+000],]
# Output data is stored here.
output = Object()
output.fuchs_sutugin=[[  0.65115939063550166E-002],]
