
# This file was generated by PartMC-mosaic.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.T_K=[[  0.29142360000000002E+003],]
input.P=[[  0.98692326671601283E+000],]
input.MW=[[  0.98000000000000000E+002],]
input.Vm=[[  0.42880001068115234E+002],]
# Output data is stored here.
output = Object()
output.gas_diffusivity=[[  0.11449280832155644E+000],]
