
# This file was generated by PartMC-mosaic.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.je=[[         5],]
input.aw=[[  0.86918676121422112E+000],]
input.molality_0=[[  0.86918676121422112E+000],]
# Output data is stored here.
output = Object()
output.molality_0=[[  0.57556452605089108E+001],]
