
# This file was generated by PartMC-mosaic.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.je=[[         5],]
input.aw=[[  0.86918676121422112E+000],]
input.molality_0=[[  0.86918676121422112E+000],]
input.a_zsr=[[  0.43507000000000001E+000,  0.63822000000000001E+001, -0.30197970000000002E+002,  0.53364699999999999E+002, -0.43442030000000003E+002,  0.13461580000000000E+002,],]
# Output data is stored here.
output = Object()
output.molality_0=[[  0.57556783407985233E+001],]
