
# This file was generated by PartMC-mosaic.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.a=[[  0.45169847930694557E-006],]
input.b=[[ -0.55848510352768968E-005],]
input.c=[[ -0.57587958019816366E-003],]
# Output data is stored here.
output = Object()
output.result=[[  0.42419304811361158E+002],]
