# Check Skywalker installation
FILE(GLOB_RECURSE SKYWALKER_FOUND_CMAKE_FILE "${SKYWALKER_INSTALL_PATH}/skywalkerConfig.cmake")

MESSAGE(STATUS "Skywalker install path : ${SKYWALKER_INSTALL_PATH}")
MESSAGE(STATUS "Skywalker found cmake config : ${SKYWALKER_FOUND_CMAKE_FILE}")

IF (SKYWALKER_FOUND_CMAKE_FILE) 
  INCLUDE(${SKYWALKER_FOUND_CMAKE_FILE})
  SET(SKYWALKER_FOUND ON)
ELSE()
  MESSAGE(FATAL_ERROR "-- Skywalker is not found at ${SKYWALKER_INSTALL_PATH}")
ENDIF()
